<option value="Accelerators">Accelerators</option>
<option value="Ageing Management">Ageing Management</option>
<option value="Atomic and Nuclear Physics">Atomic and Nuclear Physics</option>
<option value="Communication Systems">Communication Systems</option>
<option value="Computational Fluid Dynamics">Computational Fluid Dynamics</option>
<option value="Computer based systems">Computer based systems</option>
<option value="Control &  instrumentation systems">Control &  instrumentation systems</option>
<option value="Criticality Safety">Criticality Safety</option>
<option value="Cyber Security">Cyber Security</option>
<option value="Decommissioning">Decommissioning</option>
<option value="Deterministic safety analysis">Deterministic safety analysis</option>
<option value="Development of Regulations">Development of Regulations</option>
<option value="Emergency preparedness">Emergency preparedness</option>
<option value="Environmental Impact Assessment">Environmental Impact Assessment</option>
<option value="Fire Safety and Hazard Analysis">Fire Safety and Hazard Analysis</option>
<option value="Fuel Handling">Fuel Handling</option>
<option value="Fuel Management">Fuel Management</option>
<option value="Hazard Operability">Hazard Operability</option>
<option value="Industrial Radiography">Industrial Radiography</option>
<option value="Industrial Safety">Industrial Safety</option>
<option value="Inspections and Enforcements">Inspections and Enforcements</option>
<option value="Irradiators">Irradiators</option>
<option value="IT Hardware and Operating Systems">IT Hardware and Operating Systems</option>
<option value="Job Hazard Analysis">Job Hazard Analysis</option>
<option value="Management Systems">Management Systems</option>
<option value="Materials Science">Materials Science</option>
<option value="Network Technology">Network Technology</option>
<option value="NPP Technology">NPP Technology</option>
<option value="Nuclear Fuel Cycle Technology">Nuclear Fuel Cycle Technology</option>
<option value="Nuclear Law">Nuclear Law</option>
<option value="Nuclear Medicine">Nuclear Medicine</option>
<option value="Passive Systems Reliability Analysis">Passive Systems Reliability Analysis</option>
<option value="Physical Protection Systems">Physical Protection Systems</option>
<option value="Probabilistic Safety Assessment">Probabilistic Safety Assessment</option>
<option value="Radiation Application">Radiation Application</option>
<option value="Radiation Interactions and Shielding">Radiation Interactions and Shielding</option>
<option value="Radiation Protection/Health Physics">Radiation Protection/Health Physics</option>
<option value="Radioactive Waste Management">Radioactive Waste Management</option>
<option value="Radiological Impact Assessment">Radiological Impact Assessment</option>
<option value="Reactor Design">Reactor Design</option>
<option value="Reactor Operational Chemistry">Reactor Operational Chemistry</option>
<option value="Reactor Physics">Reactor Physics</option>
<option value="Reactor Safety ">Reactor Safety </option>
<option value="Reactor Thermal Hydraulics">Reactor Thermal Hydraulics</option>
<option value="Reliability analysis">Reliability analysis</option>
<option value="Risk Assessment">Risk Assessment</option>
<option value="Safety Management">Safety Management</option>
<option value="Safety Review and Consenting">Safety Review and Consenting</option>
<option value="Severe Accident Analysis">Severe Accident Analysis</option>
<option value="Seismic Analysis">Seismic Analysis</option>
<option value="Software Development">Software Development</option>
<option value="Software Reliability">Software Reliability</option>
<option value="Spent Fuel Management">Spent Fuel Management</option>
<option value="Stress Analysis ">Stress Analysis </option>
<option value="Structural Analysis">Structural Analysis</option>
<option value="Transport of Radioactive Material">Transport of Radioactive Material</option>
<option value="Two phase flow">Two phase flow</option>
<option value="X-ray">X-ray</option>
